apiVersion: v1
kind: Pod
metadata:
  name: dog-app
  labels:
    group: animal
spec:
  containers:
  - name: dog-app
    image: ubuntu:20.04
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
