apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: blue-replicaset
spec:
  selector:
    matchLabels:
      app: blue-app
  replicas: 3
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      containers:
        - name: blue-app
          image: 'yoonjeong/blue-app:1.0'
          ports:
            - containerPort: 8080