apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: snackbar     # snackbar라는 네임스페이스 안에 서비스를 생성
  labels:
    service: payment
    project: snackbar
spec:
  type: ClusterIP         # Service의 디폴트 타입이 ClusterIP이므로 따로 선언하지 않아도 ClusterIP로 생성됨
  selector:               # 파드 집합 선택자
    service: payment
    project: snackbar
  ports:
    - port: 80            # 노출할 서비스 포트
      targetPort: 8080    # 연결할 컨테이너 포트